[package]
name = "stake-deposit-interceptor"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh = "1.5.1"
bytemuck = "1.19.0"
# workaround 
getrandom = { version = "0.1.14", features = ["dummy"] }
num-derive = "0.4.2"
num-traits = "0.2.19"
solana-program = "2.0.14"
spl-associated-token-account = "5.0.1"
spl-pod = { version = "0.4.0", features = ["borsh"] }
spl-program-error = "0.5.0"
spl-program-error-derive = "0.4.1"
spl-stake-pool = "2.0.0"
thiserror = "1.0.65"

[dev-dependencies]
solana-program-test = "2.0.14"
solana-sdk = "2.0.14"
solana-vote-program = "2.0.14"
spl-token = "6.0.0"
tokio = "1.41.0"

[lib]
crate-type = ["cdylib", "lib"]
