[package]
name = "stake-deposit-interceptor"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh = "1.5.1"
# workaround 
getrandom = { version = "0.1.14", features = ["dummy"] }
solana-program = "2.0.14"
solana-sdk = "2.0.14"
spl-stake-pool = "2.0.0"

[dev-dependencies]
solana-program-test = "2.0.14"
spl-token = "6.0.0"
tokio = "1.41.0"

[lib]
crate-type = ["cdylib", "lib"]
